name: sandbox
on:
  push:
    branches: [main]
jobs:
  get_sandbox:
    runs-on: ubuntu-latest
    steps:
      # - name: Install Task
      #   uses: arduino/setup-task@v1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and run gosandbox
        run: |
          docker run -d -it --rm -p 8080:80 --name ttt docker.pkg.github.com/josephedward/gosandbox/alpha-v1:latest

          # export PATH=${PATH}:`go env GOPATH`/bin
          # wget https://github.com/josephedward/gosandbox/releases/download/v0.2.2/gosandbox_linux_386
          # chmod +x gosandbox_linux_386
          # ./gosandbox_linux_386 josephedwardwork@gmail.com ${{secrets.ACLOUD}} https://learn.acloud.guru/cloud-playground/cloud-sandboxes credentials
          # wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          # sudo apt install ./google-chrome-stable_current_amd64.deb
          # sudo apt-get update && sudo apt-get install -y libx11-dev
          # sudo apt-get install -y libxss1 libappindicator1 
          # sudo apt-get update && sudo apt-get install -y build-essential && sudo apt-get install -y libgl1-mesa-dev libnss3-dev xvfb libx11-dev
          # true | sudo apt-get install -y chromium | echo "cant install chromium" 
          # sudo Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          # export DISPLAY=:0.0