name: sandbox
on:
  push:
    branches: [main]
jobs:
  get_sandbox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and run gosandbox
      #  will result in a formatting error - easier to just build all my executables and containers in ubuntu from the start 
        run: |
          wget https://github.com/josephedward/gosandbox/releases/download/v0.2.2/gosandbox-ubuntu
          chmod +x gosandbox
          ./gosandbox 
