name: sandbox
on:
  push:
    branches: [main]
jobs:
  get_sandbox:
    runs-on: ubuntu-latest
    steps:
      # - name: Install Task
      #   uses: arduino/setup-task@v1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and run gosandbox
        run: |
          cat ${{secrets.PERSONAL_GITHUB_BOT_SECRET}} | docker login docker.pkg.github.com -u josephedward  --password-stdin
          docker pull docker.pkg.github.com/josephedward/gosandbox/alpha-v1:sha-a0dc2c2
          docker run  -e USERNAME=josephedwardwork@gmail.com -e PASSWORD=${{secrets.ACLOUD}} -e URL=https://learn.acloud.guru/cloud-playground/cloud-sandboxes -e DOWNLOAD_KEY=credentials docker.pkg.github.com/josephedward/gosandbox/alpha-v1:sha-a0dc2c2

          
