name: sandbox
on:
  push:
    branches: [main]
jobs:
  get_sandbox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and run gosandbox
      # executes - now I just need to handle deps inside the build 
        run: |
          wget https://github.com/josephedward/gosandbox/releases/download/v0.2.2/gosandbox_linux_386
          chmod +x gosandbox_linux_386
          ./gosandbox_linux_386

