name: sandbox
on:
  push:
    branches: [main]
jobs:
  get_sandbox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and run gosandbox
        run: |
          wget https://github.com/josephedward/gosandbox/releases/download/v0.2.1/gosandbox
          chmod +x gosandbox
          ./gosandbox
