name: sandbox
on:
  push:
    branches: [main]
jobs:
  get_sandbox:
    runs-on: ubuntu-latest
    steps:
      # - name: Install Task
      #   uses: arduino/setup-task@v1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and run gosandbox
        run: |
          docker login docker.pkg.github.com -u josephedward -p ${{secret.PERSONAL_GITHUB_BOT_SECRET}}
          docker pull docker.pkg.github.com/josephedward/gosandbox/alpha-v1:sha-f2982a6
          docker run -d -it --rm -p 8080:80 -e PW=${{secrets.ACLOUD}} docker.pkg.github.com/josephedward/gosandbox/alpha-v1:latest
          